#!/usr/bin/env sh

if [ -z "$ROFI_RETV" ]
then
  rofi -show power -modes "power:~/.config/sway/power-menu"
fi

if [ x"$@" = x"Hibernate" ]
then
  systemctl hibernate
  exit
fi

if [ x"$@" = x"Lock" ]
then
  loginctl lock-session
  exit
fi

if [ x"$@" = x"Logout" ]
then
  swaymsg exit
  exit
fi

if [ x"$@" = x"Poweroff" ]
then
  poweroff
  exit
fi

if [ x"$@" = x"Reboot" ]
then
  reboot
  exit
fi

if [ x"$@" = x"Sleep" ]
then
  systemctl suspend
  exit
fi

echo "Lock"
echo "Hibernate"
echo "Logout"
echo "Poweroff"
echo "Reboot"
echo "Sleep"
